#:set HASH_NAME = ["fnv_1_hasher", "fnv_1a_hasher", "seeded_nmhash32_hasher", "seeded_nmhash32x_hasher", "seeded_water_hasher"]
#:set SIZE_NAME = ["16", "256"]
module test_stdlib_chaining_maps
!! Test various aspects of the runtime system.
!! Running this program may require increasing the stack size to above 48 MBytes
!! or decreasing rand_power to 20 or less
    use testdrive, only : new_unittest, unittest_type, error_type, check
    use :: stdlib_kinds, only : dp, int8, int32
    use stdlib_hashmaps, only : chaining_hashmap_type, int_depth, int_index
    use stdlib_hashmap_chaining
    use stdlib_hashmap_wrappers

    implicit none
    private

    type dummy_type
        integer(int8), allocatable :: value(:)
    end type dummy_type

    integer(int32), parameter :: huge32 = huge(0_int32)
    real(dp), parameter       :: hugep1 = real(huge32, dp) + 1.0_dp
    integer, parameter        :: rand_power = 9
    integer, parameter        :: rand_size = 2**rand_power
    integer, parameter        :: test_size = rand_size*4
    integer, parameter        :: test_16 = 2**4
    integer, parameter        :: test_256 = 2**8

    public :: collect_stdlib_chaining_maps

contains

    !> Collect all exported unit tests
    subroutine collect_stdlib_chaining_maps(testsuite)
        !> Collection of tests
        type(unittest_type), allocatable, intent(out) :: testsuite(:)

        testsuite = [ &
            new_unittest("chaining-maps", test_chaining_maps) &
            ]

    end subroutine collect_stdlib_chaining_maps

    subroutine test_chaining_maps(error)
        !> Error handling
        type(error_type), allocatable, intent(out) :: error

        type(chaining_hashmap_type)   :: map_fnv_1_hasher_16
        type(chaining_hashmap_type)   :: map_fnv_1_hasher_256
        type(chaining_hashmap_type)   :: map_fnv_1a_hasher_16
        type(chaining_hashmap_type)   :: map_fnv_1a_hasher_256
        type(chaining_hashmap_type)   :: map_seeded_nmhash32_hasher_16
        type(chaining_hashmap_type)   :: map_seeded_nmhash32_hasher_256
        type(chaining_hashmap_type)   :: map_seeded_nmhash32x_hasher_16
        type(chaining_hashmap_type)   :: map_seeded_nmhash32x_hasher_256
        type(chaining_hashmap_type)   :: map_seeded_water_hasher_16
        type(chaining_hashmap_type)   :: map_seeded_water_hasher_256
        integer :: i
        integer(int8)             :: test_8_bits(test_size)

        call generate_vector(test_8_bits)

    #:for hash_ in HASH_NAME
        #:for size_ in SIZE_NAME
        if ("${hash_}$" == "fnv_1_hasher" .and. ${size_}$ == 16) then
            do i=1, 1024
                allocate(prev_keys_inverse(i) % value(16))
            end do

            allocate(duplicate_key_entries(33))
        else
            if (${size_}$ == 16) then
                do i=1, 1024
                    deallocate(prev_keys_inverse(i) % value)
                    allocate(prev_keys_inverse(i) % value(16))
                end do

                deallocate(duplicate_key_entries)
                allocate(duplicate_key_entries(33))
            else
                do i=1, 1024
                    deallocate(prev_keys_inverse(i) % value)
                    allocate(prev_keys_inverse(i) % value(256))
                end do

                deallocate(duplicate_key_entries)
                allocate(duplicate_key_entries(3))
            end if
        end if

        duplicate_key_entries_index = 1

        call init(map_${hash_}$_${size_}$, ${hash_}$, slots_bits=10 )

        call test_input_random_data(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        call test_inquire_data(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        call test_get_data(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        call test_removal(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return
        
        #:endfor
    #:endfor

    end subroutine


    subroutine generate_vector(test_8_bits)
        integer(int8), intent(out) :: test_8_bits(test_size)

        integer                   :: index
        real(dp)                  :: rand2(2)
        integer(int32)            :: rand_object(rand_size)

        do index=1, rand_size
            call random_number(rand2)
            if (rand2(1) < 0.5_dp) then
                rand_object(index) = ceiling(-rand2(2)*hugep1, int32) - 1
            else
                rand_object(index) = floor(rand2(2)*hugep1, int32)
            end if
        end do

        test_8_bits(:) = transfer( rand_object, 0_int8, test_size )

    end subroutine

    subroutine test_input_random_data(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(chaining_hashmap_type), intent(inout) :: map
        integer(int8), intent(in) :: test_8_bits(test_size)
        integer(int_index), intent(in) :: test_block
        class(*), allocatable :: dummy
        type(dummy_type) :: dummy_val
        integer :: index2
        type(key_type) :: key
        type(other_type) :: other
        logical :: conflict

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            if (allocated(dummy)) deallocate(dummy)
            dummy_val % value = test_8_bits( index2:index2+test_block-1 )
            allocate( dummy, source=dummy_val )
            call set ( other, dummy )
            call map_chain_entry(map, key, other, conflict )
            call check(error, .not.conflict, "Unable to map entry because of a key conflict.")
            if (allocated(error)) return
        end do

    end subroutine

    subroutine test_inquire_data(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(chaining_hashmap_type), intent(inout)  :: map
        integer(int8), intent(in)               :: test_8_bits(test_size)
        integer(int_index), intent(in)          :: test_block
        integer :: index2
        logical :: present
        type(key_type) :: key

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            call chaining_key_test(map, key, present )
            call check(error, present, "KEY not found in map KEY_TEST.")
            if (allocated(error)) return
        end do

    end subroutine

    subroutine test_get_data(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(chaining_hashmap_type), intent(inout)  :: map
        integer(int8), intent(in)               :: test_8_bits(test_size)
        integer(int_index), intent(in)          :: test_block
        integer :: index2
        type(key_type) :: key
        type(other_type) :: other
        logical :: exists

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            call get_other_chaining_data(map, key, other, exists )
            call check(error, exists, "Unable to get data because key not found in map.")
        end do

    end subroutine

    subroutine test_removal(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(chaining_hashmap_type), intent(inout)  :: map
        integer(int8), intent(in)               :: test_8_bits(test_size)
        integer(int_index), intent(in)          :: test_block
        type(key_type) :: key
        integer(int_index) :: index2, key_idx
        logical :: existed
        integer(4) :: index3 = 1

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            key_idx = ( index2/test_block ) + 1 
            if (index3 <= size(duplicate_key_entries) .and. key_idx == duplicate_key_entries(index3)) then
                index3 = index3 + 1
            else
                call remove_chaining_entry(map, key, existed)
                call check(error, existed,  "Key not found in entry removal.")
            end if
        end do

        index3 = 1
    end subroutine

end module

module test_stdlib_open_maps
!! Test various aspects of the runtime system.
!! Running this program may require increasing the stack size to above 48 MBytes
!! or decreasing rand_power to 20 or less
    use testdrive, only : new_unittest, unittest_type, error_type, check
    use :: stdlib_kinds, only : dp, int8, int32
    use stdlib_hashmaps, only : open_hashmap_type, int_depth, int_index
    use stdlib_hashmap_open
    use stdlib_hashmap_wrappers

    implicit none
    private

    type dummy_type
        integer(int8), allocatable :: value(:)
    end type dummy_type

    integer(int32), parameter :: huge32 = huge(0_int32)
    real(dp), parameter       :: hugep1 = real(huge32, dp) + 1.0_dp
    integer, parameter        :: rand_power = 9
    integer, parameter        :: rand_size = 2**rand_power
    integer, parameter        :: test_size = rand_size*4
    integer, parameter        :: test_16 = 2**4
    integer, parameter        :: test_256 = 2**8

    public :: collect_stdlib_open_maps

contains

    !> Collect all exported unit tests
    subroutine collect_stdlib_open_maps(testsuite)
        !> Collection of tests
        type(unittest_type), allocatable, intent(out) :: testsuite(:)

        testsuite = [ &
            new_unittest("open-maps", test_open_maps) &
            ]

    end subroutine collect_stdlib_open_maps

    subroutine test_open_maps(error)
        !> Error handling
        type(error_type), allocatable, intent(out) :: error

        type(open_hashmap_type)   :: map_fnv_1_hasher_16
        type(open_hashmap_type)   :: map_fnv_1_hasher_256
        type(open_hashmap_type)   :: map_fnv_1a_hasher_16
        type(open_hashmap_type)   :: map_fnv_1a_hasher_256
        type(open_hashmap_type)   :: map_seeded_nmhash32_hasher_16
        type(open_hashmap_type)   :: map_seeded_nmhash32_hasher_256
        type(open_hashmap_type)   :: map_seeded_nmhash32x_hasher_16
        type(open_hashmap_type)   :: map_seeded_nmhash32x_hasher_256
        type(open_hashmap_type)   :: map_seeded_water_hasher_16
        type(open_hashmap_type)   :: map_seeded_water_hasher_256
        integer :: i
        integer(int8)             :: test_8_bits(test_size)

        call generate_vector(test_8_bits)
    
    #:for hash_ in HASH_NAME
        #:for size_ in SIZE_NAME
        if ("${hash_}$" == "fnv_1_hasher" .and. ${size_}$ == 16) then
            do i=1, 576
                allocate(prev_keys(i) % value(16))
            end do

            allocate(duplicate_key_entries(34))
        else
            if (${size_}$ == 16) then
                do i=1, 576
                    deallocate(prev_keys(i) % value)
                    allocate(prev_keys(i) % value(16))
                end do

                deallocate(duplicate_key_entries)
                allocate(duplicate_key_entries(34))
            else
                do i=1, 576
                    deallocate(prev_keys(i) % value)
                    allocate(prev_keys(i) % value(256))
                end do

                deallocate(duplicate_key_entries)
                allocate(duplicate_key_entries(1))
            end if
        end if

        duplicate_key_entries_index = 1

        call init(map_${hash_}$_${size_}$, ${hash_}$, slots_bits=10 )

        call test_input_random_data(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        call test_inquire_data(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        call test_get_data(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        call test_removal(error, map_${hash_}$_${size_}$, test_8_bits, test_${size_}$)
        if (allocated(error)) return

        #:endfor
    #:endfor

    end subroutine


    subroutine generate_vector(test_8_bits)
        integer(int8), intent(out) :: test_8_bits(test_size)

        integer                   :: index
        real(dp)                  :: rand2(2)
        integer(int32)            :: rand_object(rand_size)

        do index=1, rand_size
            call random_number(rand2)
            if (rand2(1) < 0.5_dp) then
                rand_object(index) = ceiling(-rand2(2)*hugep1, int32) - 1
            else
                rand_object(index) = floor(rand2(2)*hugep1, int32)
            end if
        end do

        test_8_bits(:) = transfer( rand_object, 0_int8, test_size )

    end subroutine

    subroutine test_input_random_data(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(open_hashmap_type), intent(inout) :: map
        integer(int8), intent(in) :: test_8_bits(test_size)
        integer(int_index), intent(in) :: test_block
        class(*), allocatable :: dummy
        type(dummy_type) :: dummy_val
        integer :: index2
        type(key_type) :: key
        type(other_type) :: other
        logical :: conflict

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            if (allocated(dummy)) deallocate(dummy)
            dummy_val % value = test_8_bits( index2:index2+test_block-1 )
            allocate( dummy, source=dummy_val )
            call set ( other, dummy )
            call map_open_entry(map, key, other, conflict )
            call check(error, .not.conflict, "Unable to map entry because of a key conflict.")
            if (allocated(error)) return
        end do

    end subroutine

    subroutine test_inquire_data(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(open_hashmap_type), intent(inout)  :: map
        integer(int8), intent(in)               :: test_8_bits(test_size)
        integer(int_index), intent(in)          :: test_block
        integer :: index2
        logical :: present
        type(key_type) :: key

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            call open_key_test(map, key, present )
            call check(error, present, "KEY not found in map KEY_TEST.")
            if (allocated(error)) return
        end do

    end subroutine

    subroutine test_get_data(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(open_hashmap_type), intent(inout)  :: map
        integer(int8), intent(in)               :: test_8_bits(test_size)
        integer(int_index), intent(in)          :: test_block
        integer :: index2
        type(key_type) :: key
        type(other_type) :: other
        logical :: exists

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            call get_other_open_data(map, key, other, exists )
            call check(error, exists, "Unable to get data because key not found in map.")
        end do

    end subroutine

    subroutine test_removal(error, map, test_8_bits, test_block)
        type(error_type), allocatable, intent(out) :: error
        type(open_hashmap_type), intent(inout)  :: map
        integer(int8), intent(in)               :: test_8_bits(test_size)
        integer(int_index), intent(in)          :: test_block
        type(key_type) :: key
        integer(int_index) :: index2, key_idx
        logical :: existed
        integer(4) :: index3 = 1

        do index2=1, size(test_8_bits), test_block
            call set( key, test_8_bits( index2:index2+test_block-1 ) )
            key_idx = ( index2/test_block ) + 1
            if (index3 <= size(duplicate_key_entries) .and. key_idx == duplicate_key_entries(index3)) then
                index3 = index3 + 1
            else
                call remove_open_entry(map, key, existed)
                call check(error, existed,  "Key not found in entry removal.")
            end if
        end do

        index3 = 1
    end subroutine

end module


program tester
    use, intrinsic :: iso_fortran_env, only : error_unit
    use testdrive, only : run_testsuite, new_testsuite, testsuite_type
    use test_stdlib_open_maps, only : collect_stdlib_open_maps
    use test_stdlib_chaining_maps, only : collect_stdlib_chaining_maps
    implicit none
    integer :: stat, is
    type(testsuite_type), allocatable :: testsuites(:)
    character(len=*), parameter :: fmt = '("#", *(1x, a))'

    stat = 0

    testsuites = [ &
        new_testsuite("stdlib-open-maps", collect_stdlib_open_maps) &
        , new_testsuite("stdlib-chaining-maps", collect_stdlib_chaining_maps) &
        ]

    do is = 1, size(testsuites)
        write(error_unit, fmt) "Testing:", testsuites(is)%name
        call run_testsuite(testsuites(is)%collect, error_unit, stat)
    end do

    if (stat > 0) then
        write(error_unit, '(i0, 1x, a)') stat, "test(s) failed!"
        error stop
    end if
end program
